#!/usr/bin/env python3
"""Links the PC build: every object from undefined.py, plus generated stubs for whatever is still missing.
A stub prints its name and stops the program, so running the result shows what the game needs next.
Usage: port/tools/undefined.py && port/tools/link.py     -> port/build/bt3"""
import os, pathlib, re, subprocess

import sys
sys.path.insert(0, str(pathlib.Path(__file__).resolve().parent))
from toolchain import ROOT, VARIANT, WIN, PREFIX, OBJ, DATA, EXE, sdl3

B = ROOT / "port/build"

def link(objs, extra):
    common = ["-Wl,--defsym=D_3BE71C=0x3BE71C", "-Wl,--wrap=Progress_Main", f"-Wl,-Map={EXE}.map"]
    if WIN:
        # Windows: the program at a fixed address below 4 GB (no relocation: the game's 4-byte pointers and the
        # 32-bit addresses in its data tables depend on it), the game's main() wrapped for a low stack (plat_mem.c),
        # the compiler's own libraries linked in, SDL3 as SDL3.dll next to the program.
        lib = [f"-L{sdl3() / 'lib'}"] if sdl3() else []
        cmd = [PREFIX + "gcc", "-w", "-o", str(EXE)] + extra + objs + lib + \
              ["-lSDL3", "-lm", "-lwinmm", "-lws2_32", "-static-libgcc", "-Wl,-Bstatic", "-lstdc++", "-lwinpthread", "-Wl,-Bdynamic",
               "-Wl,--image-base,0x20000000", "-Wl,--disable-dynamicbase", "-Wl,--disable-reloc-section", "-Wl,--disable-high-entropy-va", "-Wl,--wrap=main",
               "-Wl,--stack,0x1000000", "-mwindows"] + common
        argsfile = B / "link.rsp"
        argsfile.write_text("\n".join('"' + a.replace('\\', '/').replace('"', '\\"') + '"' for a in cmd[1:]))
        return subprocess.run([cmd[0], "@" + str(argsfile)], capture_output=True, text=True)
    m = "-m64" if VARIANT == "clang64" else "-m32"
    # 64-bit: the program below 4 GB and clear of the PS2 regions (plat_mem.c); the game's main() on a low stack
    base64 = ["-Wl,-Ttext-segment=0x20000000", "-Wl,--wrap=main"] if VARIANT == "clang64" else []
    # -rpath $ORIGIN/lib: a release folder carries its own SDL3 in lib/
    return subprocess.run(["gcc", m, "-no-pie", "-w", "-o", str(EXE)] + extra + objs +
                          ["-static-libstdc++", "-static-libgcc", "-Wl,-Bstatic", "-lstdc++", "-Wl,-Bdynamic", "-lm", "-lpthread", "-lSDL3", "-rdynamic",
                           "-Wl,-rpath,$ORIGIN/lib"] + common + base64, capture_output=True, text=True)

def main():
    objs = [str(o) for o in sorted(OBJ.glob("*.o")) + sorted(DATA.glob("*.o"))]
    r = link(objs, [])  # first pass: ask the linker what nobody provides (the host C library included)
    need = sorted(set(re.findall(r"undefined reference to `(\w+)'", r.stderr)))
    lines = ['/* Generated by port/tools/link.py: one stub per symbol the PC build does not provide yet. */',
             'extern int printf(const char *, ...);', 'extern void exit(int);',
             'static void missing(const char *n) { printf("bt3: not implemented yet: %s\\n", n); exit(3); }']
    lines += [f'void {s}(void) {{ missing("{s}"); }}' for s in need]
    (B / "gen").mkdir(exist_ok=True)
    (B / "gen/stubs.c").write_text("\n".join(lines) + "\n")
    (B / "stubs.txt").write_text("\n".join(need) + "\n")
    r = link(objs, [str(B / "gen/stubs.c")])
    errs = [l for l in r.stderr.splitlines() if "multiple definition" in l or "undefined reference" in l or "rror" in l]
    print(f"{len(need)} stubs; link {'OK -> ' + str(EXE.relative_to(ROOT)) if r.returncode == 0 else 'FAILED'}; {len(errs)} error lines")
    for l in errs[:12]:
        print("  " + l[-160:])
    if r.returncode == 0:
        # where the game's own variables lie in this program (for the state checksum; port/src/gs/state.c)
        d = subprocess.run([sys.executable, str(ROOT / "port/tools/make_state.py")], capture_output=True, text=True)
        if d.returncode:
            print((d.stdout + d.stderr).strip()[-300:])
            sys.exit(1)
    if r.returncode == 0 and (DATA / "SKELETON").exists():
        # built from the blank data tables: the program needs the list of where their values are on the user's disc
        d = subprocess.run([sys.executable, str(ROOT / "port/tools/make_dat.py")], capture_output=True, text=True)
        print((d.stdout + d.stderr).strip()[-300:])
        if d.returncode:
            sys.exit(1)
    if r.returncode:
        sys.exit(1)

main()
